# fly.toml app configuration file generated for funty on 2024-05-17T14:09:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'funty'
kill_signal = "SIGINT"
primary_region = 'atl'
console_command = '/rails/bin/rails console'

[build]
  [build.args]
    RUBY_VERSION = "3.1.2"

[deploy]
  release_command = './bin/rails db:prepare'
  image = "flyio/redis:6.2.6"

[env]
  PORT = "3000"
  SERVER_COMMAND = "bundle exec puma"

[processes]
app = "bin/rails server"
worker = "bundle exec sidekiq -C config/sidekiq.yml"
release_command = "bin/rails db:prepare"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  swap_size_mb = 512

[mounts]
  source = "funty_data"
  destination = "/data"

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

