# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    parallelism: 1
    working_directory: ~/funty
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          PGHOST: localhost
          PGUSER: funty
          RAILS_ENV: test
      - image: postgres:14.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: funty_test
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: flashcards-{{ checksum "Gemfile.lock" }}

      - run: bundle lock --add-platform x86_64-linux
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          # remove space between { {
          key: project-name-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run: bundle exec rake assets:precompile
      - run: bundle exec rspec

workflows:
  build:
    jobs:
      - build
