default: &default
  adapter: postgresql
  encoding: UTF-8
  host: localhost
  user: postgres
  password: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: funty_development

test:
  <<: *default
  database: funty_test

production:
  <<: *default
  database: funty_prod
